### ISSUE TITLE
存在bug，设置serverip为127.0.0.1,可以正常本地使用（同一台），改为公网IP，无法连接

### ISSUE THREAD

**Issue by wu5liu6qi7** [CodeSecurityTeam/frp#2]
![image](https://github.com/user-attachments/assets/93dd4a36-9317-481d-86a7-f803325fb55d)

**Comment by CTF-MissFeng** [comment]
> ![image](https://private-user-images.githubusercontent.com/161825533/356176823-93dd4a36-9317-481d-86a7-f803325fb55d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjU2NzMsIm5iZiI6MTcyMzE2NTM3MywicGF0aCI6Ii8xNjE4MjU1MzMvMzU2MTc2ODIzLTkzZGQ0YTM2LTkzMTctNDgxZC04NmE3LWY4MDMzMjVmYjU1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwMTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjE3NDMzNmUxZTRjZDNlYTViN2EzMDNkN2NkOTIzYzMwNzg4ZmI0NjIyMzU4YjgwMTRiMGE2NmU2NzM1ZGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-U_09H5KFZkU4qqczjpRRO_GMcXZhJ_MvgWrGtlfbxg)

frpc的serverip为公网 IP，frps的监听地址是否为0.0.0.0或本机网卡 IP，监听的端口是否防火墙开放

**Comment by wu5liu6qi7** [comment]
可以了，改成0.0.0.0,就可以了，谢谢大佬
