### ISSUE TITLE
base64.Decode err: illegal base64 data at input byte 0

### ISSUE THREAD

**Issue by Arreb0-1** [CodeSecurityTeam/frp#3]
![error](https://github.com/user-attachments/assets/3c66e5a4-2c23-4594-b2c4-79ea6801d5c3)

师傅这是什么问题

**Comment by CTF-MissFeng** [comment]
> ![错误](https://private-user-images.githubusercontent.com/154102534/356230481-3c66e5a4-2c23-4594-b2c4-79ea6801d5c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjU2MTAsIm5iZiI6MTcyMzE2NTMxMCwicGF0aCI6Ii8xNTQxMDI1MzQvMzU2MjMwNDgxLTNjNjZlNWE0LTJjMjMtNDU5NC1iMmM0LTc5ZWE2ODAxZDVjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwMTAxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjIxZmU0ODMzYzIwOTIwYjE5ODhhMDhhN2Y0ODIzZTRhODUwMTQxYjAzNTM3NTViMGY4YzY5YmNiYmE0MDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zbcH8MXBc4EwQHUVLel0Cj8yGkrfLjKJSnRuGrwgcgg)
> 
> 师傅这是什么问题

请检查oss加密文本是否有换行符等其它符号呢
